default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: stay_app_development

test:
  <<: *default
  database: stay_app_test